#!/usr/bin/with-contenv bash

cp /usr/local/openvpn_as/etc/as_templ.conf /usr/local/openvpn_as/etc/as.conf
echo "If this is the first time booting up, please use the following information to login"
echo "-----------------------------------------------------------------------------"
grep -i 'password.$' /usr/local/openvpn_as/init.log
echo "-----------------------------------------------------------------------------"
echo "Please make sure to change this password"
echo "If you change your password and then forget it, please use the following command to reset" 
echo "-----------------------------------------------------------------------------"
echo "/usr/local/openvpn_as/scripts/sacli --user "openvpn" --new_pass=<PASSWORD> SetLocalPassword"
echo "systemctl restart openvpnas"
echo "-----------------------------------------------------------------------------"
